// DRESK - Server CVars
// Server CVars

#define CVAR_GAMEMODE_KLESHIKWEAPONS_ENABLED								"kleshik_server_gamemode_KleshikWeapons_Enabled"
#define CVAR_GAMEMODE_KLESHIKMONSTERS_ENABLED								"kleshik_server_gamemode_KleshikMonsters_Enabled"
#define CVAR_GAMEMODE_GYROPHYSICS_ENABLED									"kleshik_server_gamemode_GyroPhysics_Enabled"
#define CVAR_GAMEMODE_GYROPHYSICS_DETAILENTITIES							"kleshik_server_gamemode_GyroPhysics_DetailEntities"
#define CVAR_GAMEMODE_HIPNOTIC_ENABLED										"kleshik_server_gamemode_Hipnotic_Enabled"
#define CVAR_GAMEMODE_HIPNOTIC_LEGACYITEMS									"kleshik_server_gamemode_Hipnotic_LegacyItems"
#define CVAR_GAMEMODE_HIPNOTIC_USEHIPNOTICMONSTERREPLACEMENTS				"kleshik_server_gamemode_Hipnotic_UseHipnoticMonsterReplacements"
#define CVAR_GAMEMODE_HIPNOTIC_ALLINHERITGRAVITY							"kleshik_server_gamemode_Hipnotic_AllInheritGravity"
#define CVAR_GAMEMODE_ROGUE_ENABLED											"kleshik_server_gamemode_Rogue_Enabled"
#define CVAR_GAMEMODE_ROGUE_USEROGUEMONSTERREPLACEMENTS						"kleshik_server_gamemode_Rogue_UseRogueMonsterReplacements"
#define CVAR_GAMEMODE_TRAVAIL_ENABLED										"kleshik_server_gamemode_Travail_Enabled"

#define CVAR_BLOODGORE_ALIGNCORPSESWITHSURFACENORMAL						"kleshik_server_BloodGore_AlignCorpsesWithSurfaceNormal"
#define CVAR_BLOODGORE_ALLGIBSPERSISTENT									"kleshik_server_BloodGore_AllGibsPersistent"
#define CVAR_BLOODGORE_BLEEDATHEALTHPERCENTILE								"kleshik_server_BloodGore_BleedAtHealthPercentile"
#define CVAR_BLOODGORE_BLOODSHOWERAMOUNTONDEATH								"kleshik_server_BloodGore_BloodShowerAmountOnDeath"
#define CVAR_BLOODGORE_PLAYERBODYQUESIZE									"kleshik_server_BloodGore_PlayerBodyQueSize"
#define CVAR_BLOODGORE_CORPSESGIBBABLEWITHRADIUSDAMAGE						"kleshik_server_BloodGore_CorpsesGibbableWithRadiusDamage"
#define CVAR_BLOODGORE_CORPSETWITCHMAXIMUM									"kleshik_server_BloodGore_CorpseTwitchMaximum"
#define CVAR_BLOODGORE_DAMAGEABLEGIBS										"kleshik_server_BloodGore_DamageableGibs"
#define CVAR_BLOODGORE_DIRECTIONALGIBS										"kleshik_server_BloodGore_DirectionalGibs"
#define CVAR_BLOODGORE_EXPLOSIVESALWAYSGIB									"kleshik_server_BloodGore_ExplosivesAlwaysGib"
#define CVAR_BLOODGORE_MAXIMUMGIBSONDEATH									"kleshik_server_BloodGore_MaximumGibsOnDeath"

#define CVAR_COOP_DISABLEFRIENDLYFIRE										"kleshik_server_coop_DisableFriendlyFire"
#define CVAR_COOP_FULLBRIGHTPLAYERS											"kleshik_server_coop_FullBrightPlayers"
#define CVAR_COOP_BROADCASTCENTERPRINTS										"kleshik_server_coop_BroadcastCenterprints"
#define CVAR_COOP_REFILLHEALTHANDARMOREVERYLEVEL							"kleshik_server_coop_RefillHealthAndArmorEveryLevel"
#define CVAR_COOP_RESPAWNATDEATHLOCATION_ALLOW								"kleshik_server_coop_RespawnAtDeathLocation_Allow"
#define CVAR_COOP_RESPAWNATDEATHLOCATION_REUSETIME							"kleshik_server_coop_RespawnAtDeathLocation_ReuseTime"
#define CVAR_COOP_PLAYERBACKPACKSYSTEM										"kleshik_server_coop_PlayerBackpackSystem"
#define CVAR_COOP_BROADCASTPLAYERBACKPACKPICKUPS							"kleshik_server_coop_BroadcastPlayerBackpackPickups"
#define CVAR_COOP_SUPPRESSTELEFRAGONSPAWN									"kleshik_server_coop_SuppressTelefragOnSpawn"
#define CVAR_COOP_SHAREDWEAPONSPOOL											"kleshik_server_coop_SharedWeaponsPool"
#define CVAR_COOP_SHAREDAMMOPOOL											"kleshik_server_coop_SharedAmmoPool"
#define CVAR_COOP_MIRRORFRIENDLYDAMAGE										"kleshik_server_coop_MirrorFriendlyDamage"

#define CVAR_PERSONALTELEPORTER_REUSEDELAYTIME								"kleshik_server_PersonalTeleporter_ReuseDelayTime"
#define CVAR_PERSONALTELEPORTER_ALLOWKEYTELEPORTS							"kleshik_server_PersonalTeleporter_AllowKeyTeleports"
#define CVAR_PERSONALTELEPORTER_ALLOWDOORKEYTELEPORTS						"kleshik_server_PersonalTeleporter_AllowDoorKeyTeleports"

#define CVAR_PLAYERMODEL_PRECACHEALL_QUAKE2									"kleshik_server_PlayerModel_PrecacheAll_Quake2"
#define CVAR_PLAYERMODEL_ALLOWPLAYERMODELCHANGES							"kleshik_server_PlayerModel_AllowPlayerModelChanges"
#define CVAR_PLAYERMODEL_ALLOWPLAYERMODELTYPE_QUAKE2						"kleshik_server_PlayerModel_AllowPlayerModelType_Quake2"
#define CVAR_PLAYERMODEL_REUSEDELAYTIME										"kleshik_server_PlayerModel_ReuseDelayTime"
#define CVAR_PLAYERMODEL_CROUCH_INTERACTIVITYLEVEL							"kleshik_server_PlayerModel_Crouch_InteractivityLevel"
#define CVAR_PLAYERMODEL_CROUCH_ATTACKREFIREMOD								"kleshik_server_PlayerModel_Crouch_AttackRefireMod"
#define CVAR_PLAYERMODEL_CROUCH_DAMAGERECEIVEDMOD							"kleshik_server_PlayerModel_Crouch_DamageReceivedMod"

#define CVAR_PLAYERDEATH_BLOODEXPLOSIONPERCENTCHANCE						"kleshik_server_PlayerDeath_BloodExplosionPercentChance"
#define CVAR_PLAYERDEATH_HUDSTINGERPERCENTCHANCE							"kleshik_server_PlayerDeath_HUDStingerPercentChance"
#define CVAR_PLAYERDEATH_ELITEMONSTERPERCENTCHANCE							"kleshik_server_PlayerDeath_EliteMonsterPercentChance"

#define CVAR_PLAYER_RESPAWNTIME												"kleshik_server_player_RespawnTime"
#define CVAR_PLAYER_ADDGROUNDVELOCITYTOJUMP									"kleshik_server_player_AddGroundVelocityToJump"
#define CVAR_PLAYER_DROPPOWERUPSONDEATH										"kleshik_server_player_DropPowerupsOnDeath"
#define CVAR_PLAYER_RESPAWNUSINGLASTEQUIPPEDWEAPON							"kleshik_server_player_RespawnUsingLastEquippedWeapon"

#define CVAR_WORLD_ENABLERANDOMHUDSTINGERS									"kleshik_server_world_EnableRandomHUDStingers"
#define CVAR_WORLD_ENABLERANDOMWORLDLIGHTPULSATIONS							"kleshik_server_world_EnableRandomWorldLightPulsations"
#define CVAR_WORLD_CREATESPAWNPOINTMODELS									"kleshik_server_world_CreateSpawnPointModels"
#define CVAR_WORLD_DISABLEALLDYNAMICLIGHTPULSATIONS							"kleshik_server_world_DisableAllDynamicLightPulsations"
#define CVAR_WORLD_SPAWNADDITIONALAMBIENTSOUNDS								"kleshik_server_world_SpawnAdditionalAmbientSounds"
#define CVAR_WORLD_PLAYRANDOMWORLDSOUNDS									"kleshik_server_world_PlayRandomWorldSounds"
#define CVAR_WORLD_NORMALLIGHTMAPANIMATION									"kleshik_server_world_NormalLightmapAnimation"
#define CVAR_WORLD_NIGHTANDDAY_CHANGEINTERVAL								"kleshik_server_world_NightAndDay_ChangeInterval"
#define CVAR_WORLD_NIGHTANDDAY_MINLIGHTLEVEL								"kleshik_server_world_NightAndDay_MinLightLevel"
#define CVAR_WORLD_NIGHTANDDAY_MAXLIGHTLEVEL								"kleshik_server_world_NightAndDay_MaxLightLevel"
#define CVAR_WORLD_BRUSHCRUSHESINSTANTKILL									"kleshik_server_world_BrushCrushesInstantKill"
#define CVAR_WORLD_SPAWNFADINGCOPYATTELEPORT								"kleshik_server_world_SpawnFadingCopyAtTeleport"

#define CVAR_MISC_ADVANCEDSTATISTICSATINTERMISSION							"kleshik_server_misc_AdvancedStatisticsAtIntermission"
#define CVAR_MISC_BROADCASTPLAYERCHEATS										"kleshik_server_misc_BroadcastPlayerCheats"
#define CVAR_MISC_PLAYERSCORESATINTERMISSION								"kleshik_server_misc_PlayerScoresAtIntermission"

#define CVAR_ITEM_FADEUNAVAILABLEITEMS										"kleshik_server_item_FadeUnavailableItems"

#define CVAR_ITEM_COOPITEMSRESPAWN											kleshik_server_item_CoopItemsRespawn

#define CVAR_ITEM_POWERUP_GLOBALPICKUPSOUNDS								"kleshik_server_item_Powerup_GlobalPickupSounds"
#define CVAR_ITEM_POWERUP_TIMESADDED										"kleshik_server_item_Powerup_TimesAdded"
#define CVAR_ITEM_POWERUP_INVISIBILITY_USEALPHALEVEL						"kleshik_server_item_Powerup_Invisibility_UseAlphaLevel"
#define CVAR_ITEM_RESPAWNTIME_AMMOHEALTH									"kleshik_server_item_RespawnTime_AmmoHealth"
#define CVAR_ITEM_RESPAWNTIME_ARMOR											"kleshik_server_item_RespawnTime_Armor"
#define CVAR_ITEM_RESPAWNTIME_MEGAHEALTH									"kleshik_server_item_RespawnTime_MegaHealth"
#define CVAR_ITEM_RESPAWNTIME_POWERUP										"kleshik_server_item_RespawnTime_Powerup"

#define CVAR_ITEM_DISPLAYFLOATINGKEYSABOVEPLAYER							"kleshik_server_item_DisplayFloatingKeysAbovePlayer"
#define CVAR_ITEM_DISPLAYFLOATINGWEAPONABOVEPLAYER							"kleshik_server_item_DisplayFloatingWeaponAbovePlayer"

#define CVAR_ITEM_DISABLEPICKUPMESSAGE_AMMO									"kleshik_server_item_DisablePickupMessage_Ammo"
#define CVAR_ITEM_DISABLEPICKUPMESSAGE_ARMOR								"kleshik_server_item_DisablePickupMessage_Armor"
#define CVAR_ITEM_DISABLEPICKUPMESSAGE_BACKPACK								"kleshik_server_item_DisablePickupMessage_Backpack"
#define CVAR_ITEM_DISABLEPICKUPMESSAGE_HEALTH								"kleshik_server_item_DisablePickupMessage_Health"
#define CVAR_ITEM_DISABLEPICKUPMESSAGE_WEAPON								"kleshik_server_item_DisablePickupMessage_Weapon"
#define CVAR_ITEM_DISABLEPICKUPMESSAGE_POWERUP								"kleshik_server_item_DisablePickupMessage_Powerup"

#define CVAR_EXPLODINGITEMBOX_PERCENTCHANCE									"kleshik_server_ExplodingItemBox_PercentChance"
#define CVAR_EXPLODINGITEMBOX_DAMAGE										"kleshik_server_ExplodingItemBox_Damage"
#define CVAR_EXPLODINGITEMBOX_INCLUDEITEMRESPAWNS							"kleshik_server_ExplodingItemBox_IncludeItemRespawns"
#define CVAR_EXPLODINGITEMBOX_INDEATHMATCH									"kleshik_server_ExplodingItemBox_InDeathmatch"

#define CVAR_FLASHLIGHT_MAXBATTERYCHARGE									"kleshik_server_FlashLight_MaxBatteryCharge"
#define CVAR_FLASHLIGHT_MINIMUMAMBIENTLEVEL									"kleshik_server_FlashLight_MinimumAmbientLevel"

#define CVAR_THROWABLEFLARES_FLARELIFETIME									"kleshik_server_ThrowableFlares_FlareLifeTime"
#define CVAR_THROWABLEFLARES_FLARELIGHTPOWER								"kleshik_server_ThrowableFlares_FlareLightPower"
#define CVAR_THROWABLEFLARES_FLAREREFIRETIME								"kleshik_server_ThrowableFlares_FlareRefireTime"
#define CVAR_THROWABLEFLARES_FLARETOUCHDAMAGE								"kleshik_server_ThrowableFlares_FlareTouchDamage"

#define CVAR_MONSTER_ALLOWDAMAGEFORCE										"kleshik_server_monster_AllowDamageForce"
#define CVAR_MONSTER_APPLYADDITIONALLIFTVELOCITY							"kleshik_server_monster_ApplyAdditionalLiftVelocity"
#define CVAR_MONSTER_SEETHROUGHWATER										"kleshik_server_monster_SeeThroughWater"
#define CVAR_MONSTER_APPLYRANDOMAESTHETICS									"kleshik_server_monster_ApplyRandomAesthetics"
#define CVAR_MONSTER_ENABLERANDOMMONSTERSUBSTITUTIONS						"kleshik_server_monster_EnableRandomMonsterSubstitutions"
#define CVAR_MONSTER_MOVEMENTMULTIPLIER										"kleshik_server_monster_MovementMultiplier"
#define CVAR_MONSTER_MOVEMENTMAXIMUM										"kleshik_server_monster_MovementMaximum"
#define CVAR_MONSTER_GLOBALALPHALEVEL										"kleshik_server_monster_GlobalAlphaLevel"
#define CVAR_MONSTER_SKILLLEVELFORLEADINGPROJECTILES						"kleshik_server_monster_SkillLevelForLeadingProjectiles"
#define CVAR_MONSTER_SPAWNADDITIONALCREATURES								"kleshik_server_monster_SpawnAdditionalMonsters"
#define CVAR_MONSTER_SPAWNEDMONSTER_TELEPORTWITHORIGINALMONSTER				"kleshik_server_monster_SpawnedMonster_TeleportWithOriginalMonster"
#define CVAR_MONSTER_MONSTERSROAM											"kleshik_server_monster_MonstersRoam"
#define CVAR_MONSTER_DEATHSOUNDHASNOATTENUATION								"kleshik_server_monster_DeathSoundHasNoAttenuation"
#define CVAR_MONSTER_DROPADDITIONALITEMS									"kleshik_server_monster_DropAdditionalItems"
#define CVAR_MONSTER_SHALRATH_MISSILEEXPLODETIME							"kleshik_server_monster_Shalrath_MissileExplodeTime"
#define CVAR_MONSTER_WRATH_MISSILEEXPLODETIME								"kleshik_server_monster_Wrath_MissileExplodeTime"
#define CVAR_MONSTER_FLISKER_CORPSEBURSTPERCENTCHANCE						"kleshik_server_monster_Flisker_CorpseBurstPercentChance"

#define CVAR_ELITEMONSTER_BASEPERCENTCHANCE									"kleshik_server_EliteMonster_BasePercentChance"
#define CVAR_ELITEMONSTER_INITIALCONTACTHUDSTINGER							"kleshik_server_EliteMonster_InitialContactHUDStinger"
#define CVAR_ELITEMONSTER_PERCENTMONSTERHEALTHGRANTEDTOPLAYERSONDEATH		"kleshik_server_EliteMonster_PercentMonsterHealthGrantedToPlayersOnDeath"
#define CVAR_ELITEMONSTER_MAXMONSTERHEALTHGRANTEDTOPLAYERSONDEATH			"kleshik_server_EliteMonster_MaxMonsterHealthGrantedToPlayersOnDeath"

#define CVAR_WEAPON_PROJECTILESOWNERVELOCITYRATIO							"kleshik_server_weapon_ProjectilesOwnerVelocityRatio"
#define CVAR_WEAPON_DETAILEDNAILTOUCH										"kleshik_server_weapon_DetailedNailTouch"
#define CVAR_WEAPON_ALLSHOTGUNS_PERBULLETDAMAGE								"kleshik_server_weapon_AllShotguns_PerBulletDamage"
#define CVAR_WEAPON_THUNDERBOLT_BEAMDISCHARGES								"kleshik_server_weapon_Thunderbolt_BeamDischarges"
#define CVAR_WEAPON_PROXIMITYGUN_ALLOWALTFIREDETONATION						"kleshik_server_weapon_ProximityGun_AllowAltFireDetonation"
#define CVAR_WEAPON_PROXIMITYGUN_MAXBOMBS									"kleshik_server_weapon_ProximityGun_MaxBombs"
#define CVAR_WEAPON_PROXIMITYGUN_TRIGGERONOTHERBOMBS						"kleshik_server_weapon_ProximityGun_TriggerOnOtherBombs"
#define CVAR_WEAPON_PROXIMITYGUN_BOMBLIFETIME								"kleshik_server_weapon_ProximityGun_BombLifetime"

#define CVAR_AMMO_MAXSHELLS													"kleshik_server_ammo_MaxShells"
#define CVAR_AMMO_MAXNAILS													"kleshik_server_ammo_MaxNails"
#define CVAR_AMMO_MAXROCKETS												"kleshik_server_ammo_MaxRockets"
#define CVAR_AMMO_MAXCELLS													"kleshik_server_ammo_MaxCells"
#define CVAR_AMMO_INFINITE													"kleshik_server_ammo_infinite"

// Auto CVars
float	SG_AUTOCVAR(kleshik_server_gamemode_Hipnotic_AllInheritGravity);

float	SG_AUTOCVAR(kleshik_server_BloodGore_BleedAtHealthPercentile);
float	SG_AUTOCVAR(kleshik_server_BloodGore_CorpseTwitchMaximum);
float	SG_AUTOCVAR(kleshik_server_BloodGore_DirectionalGibs);

float	SG_AUTOCVAR(kleshik_server_coop_DisableFriendlyFire);

float	SG_AUTOCVAR(kleshik_server_ammo_infinite);

float	SG_AUTOCVAR(kleshik_server_PlayerModel_Crouch_AttackRefireMod);
float	SG_AUTOCVAR(kleshik_server_PlayerModel_Crouch_DamageReceivedMod);

float	SG_AUTOCVAR(kleshik_server_FlashLight_MinimumAmbientLevel);

float	SG_AUTOCVAR_INIT(CVAR_ITEM_COOPITEMSRESPAWN);
// float	autocvar_kleshik_server_item_CoopItemsRespawn;
// CVAR_ITEM_COOPITEMSRESPAWN

float	SG_AUTOCVAR(kleshik_server_ThrowableFlares_FlareLightPower);

float	SG_AUTOCVAR(kleshik_server_item_DisablePickupMessage_Ammo);
float	SG_AUTOCVAR(kleshik_server_item_DisablePickupMessage_Armor);
float	SG_AUTOCVAR(kleshik_server_item_DisablePickupMessage_Backpack);
float	SG_AUTOCVAR(kleshik_server_item_DisablePickupMessage_Health);
float	SG_AUTOCVAR(kleshik_server_item_DisablePickupMessage_Weapon);
float	SG_AUTOCVAR(kleshik_server_item_DisablePickupMessage_Powerup);

float	SG_AUTOCVAR(kleshik_server_monster_AllowDamageForce);
float	SG_AUTOCVAR(kleshik_server_monster_ApplyAdditionalLiftVelocity);
float	SG_AUTOCVAR(kleshik_server_monster_MonstersRoam);
float	SG_AUTOCVAR(kleshik_server_monster_SeeThroughWater);

float	SG_AUTOCVAR(kleshik_server_player_AddGroundVelocityToJump);

float	SG_AUTOCVAR(kleshik_server_weapon_AllShotguns_PerBulletDamage);
float	SG_AUTOCVAR(kleshik_server_weapon_DetailedNailTouch);
float	SG_AUTOCVAR(kleshik_server_weapon_ProximityGun_BombLifetime);
float	SG_AUTOCVAR(kleshik_server_weapon_ProximityGun_MaxBombs);
float	SG_AUTOCVAR(kleshik_server_weapon_ProximityGun_TriggerOtherBombs);
float	SG_AUTOCVAR(kleshik_server_weapon_Thunderbolt_BeamDischarges);

float	SG_AUTOCVAR(kleshik_server_world_NightAndDay_ChangeInterval);

float	SG_AUTOCVAR(sv_gravity);
float	SG_AUTOCVAR(sv_maxvelocity);